### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by itomac** [ladisk/pyidi#6]
I am using python3 on Linux Debian (Buster). Installation of ```pyidi``` package using pip3 went smoothly, but then in the jupyter notebook when I have invoked a command ```import pyidi``` I have got an error message that Tkinter module is missing:
```ModuleNotFoundError: No module named 'tkinter'```
so I had to installed it manually.

**Comment by jankoslavic** [comment]
Thanks @itomac! We will look into details!

**Comment by klemengit** [comment]
In order to install `tkinter`, run:
`sudo apt-get install python-tk`

If you install the official distribution of python, `tkinter` is already included.
